on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  converge:
    name: Converge
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install werf
        uses: werf/actions/install@v1.2

      - name: Log in to registry
        # This is where you will update the personal access token to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Run echo
        run: |
          werf version
          docker version
          echo $GITHUB_REPOSITORY
          echo $GITHUB_REF_NAME
      - name: Run Build
        run: |
          . $(werf ci-env github --as-file) 
          werf export web --tag ghcr.io/$GITHUB_REPOSITORY:$GITHUB_REF_NAME

 deploy:
    name: Deploy
    needs: converge
    runs-on: ubuntu-latest
    steps:
      - name: Helm
        uses: azure/setup-helm@v1
        with:
          version: v3
      - name: ConfigCreate
        run: |
          mkdir ~/.kube/
          echo "${{ secrets.KUBERCONFIG }}" | base64 -d > config
          mv config ~/.kube/
          helm upgrade -i --kubeconfig ~/.kube/config "webclient" ".helm" --set global.IngressDomain=rarime.com --set "image.repository=ghcr.io/${GITHUB_REPOSITORY}" --set "image.tag=${GITHUB_REF_NAME}" --create-namespace --namespace rarime-landing-prod-rarime
